# Generated by Django 4.0.5 on 2022-07-02 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.FileField(default='companydefault.jpg', upload_to='companylogo')),
                ('website', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=200)),
                ('profile_pic', models.ImageField(default='defaultprofile.jpg', upload_to='profile_pics')),
                ('age', models.IntegerField(null=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('biography', models.CharField(default='', max_length=500)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Country')),
                ('twitter', models.CharField(default='', max_length=500)),
                ('instagram', models.CharField(default='', max_length=500)),
                ('linkedin', models.CharField(default='', max_length=500)),
                ('facebook', models.CharField(default='', max_length=500)),
                ('emploment_status', models.CharField(choices=[('EMPLOYED', 'Employed'), ('UNEMPLOYED', 'Unemployed')], default=(), max_length=200)),
                ('occupation', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('salary', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineJob.company')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('job', models.ManyToManyField(related_name='applicant', to='OnlineJob.job')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
            },
        ),
    ]
