# Generated by Django 4.0.5 on 2022-07-04 22:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('document', models.FileField(upload_to='resumes/%Y%m%d')),
                ('submissiondate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Passed', 'Passed'), ('Rejected', 'Rejected')], default=(('Pending', 'Pending'),), max_length=50)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.FileField(default='companydefault.jpg', upload_to='companylogo')),
                ('website', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=200)),
                ('profile_pic', models.ImageField(default='defaultprofile.jpg', upload_to='profile_pics')),
                ('age', models.IntegerField(null=True)),
                ('email', models.EmailField(default='', max_length=254)),
                ('biography', models.CharField(default='', max_length=500)),
                ('country', django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Country')),
                ('twitter', models.CharField(blank=True, default='', max_length=500)),
                ('instagram', models.CharField(blank=True, default='', max_length=500)),
                ('linkedin', models.CharField(blank=True, default='', max_length=500)),
                ('facebook', models.CharField(blank=True, default='', max_length=500)),
                ('employment_status', models.CharField(choices=[('EMPLOYED', 'Employed'), ('UNEMPLOYED', 'Unemployed')], default=(), max_length=200)),
                ('occupation', models.CharField(default='', max_length=200)),
                ('city', models.CharField(default='', max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='', max_length=200)),
                ('position', models.CharField(default='', max_length=200)),
                ('date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(default='')),
                ('document', models.FileField(blank=True, upload_to='documents/%Y%m%d')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=200)),
                ('salary', models.IntegerField(default=0)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineJob.company')),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='ControlPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Submitted', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Passed', 'Passed'), ('Rejected', 'Rejected')], max_length=50)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineJob.application')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineJob.company')),
                ('resume', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='OnlineJob.note')),
            ],
            options={
                'verbose_name': 'Control Panel',
                'verbose_name_plural': ' Control Panels',
            },
        ),
        migrations.AddField(
            model_name='application',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='OnlineJob.company'),
        ),
        migrations.AddField(
            model_name='application',
            name='jobname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='OnlineJob.applicant'),
        ),
        migrations.AddField(
            model_name='application',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineJob.applicant'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineJob.job'),
        ),
        migrations.AddField(
            model_name='applicant',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
