# Generated by Django 4.0.5 on 2022-07-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJob', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='emploment_status',
            new_name='employment_status',
        ),
    ]
