# Generated by Django 4.0.5 on 2022-07-10 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJob', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlpanel',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineJob.applicant'),
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
