# Generated by Django 4.0.5 on 2022-07-03 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJob', '0002_rename_emploment_status_profile_employment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='city',
            field=models.CharField(default='', max_length=200),
        ),
    ]
