# Generated by Django 4.0.5 on 2022-07-03 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJob', '0003_profile_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='document',
            field=models.FileField(null=True, upload_to='resume'),
        ),
    ]
