# Generated by Django 4.0.5 on 2022-07-03 15:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('OnlineJob', '0004_applicant_document'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('text', models.TextField(default='')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineJob.company')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OnlineJob.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
