# Generated by Django 4.0.5 on 2022-07-03 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJob', '0005_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Note', 'verbose_name_plural': 'Notes'},
        ),
    ]
