# Generated by Django 4.0.5 on 2022-07-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJob', '0006_alter_note_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='company',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='note',
            name='position',
            field=models.CharField(default='', max_length=200),
        ),
    ]
