# Generated by Django 4.0.5 on 2022-07-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJob', '0007_alter_note_company_alter_note_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='document',
            field=models.FileField(blank=True, upload_to='note'),
        ),
    ]
