# Generated by Django 4.0.5 on 2022-07-03 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OnlineJob', '0008_note_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='document',
            field=models.FileField(blank=True, upload_to='documents/%Y%m%d'),
        ),
    ]
